---
booktitle: Proceedings of the AI for African Languages Conference 2025
shortname: AfriLang
year: '2025'
volume: '314'
start: &1 2025-10-10
end: 2025-10-10
published: 2026-02-27
conference_number: '1'
sections:
- name: Preface
  title: Preface
- name: Invited Papers
  title: Invited Papers
- name: Contributed Papers
  title: Contributed Papers
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: afrilang25
month: 0
cycles: false
bibtex_editor: Bainomugisha, Engineer and Mwebaze, Ernest and Kimera, Richard and
  Nabende, Joyce Nakatumba and Katumba, Andrew and Quinn, John
editor:
- given: Engineer
  family: Bainomugisha
- given: Ernest
  family: Mwebaze
- given: Richard
  family: Kimera
- given: Joyce Nakatumba
  family: Nabende
- given: Andrew
  family: Katumba
- given: John
  family: Quinn
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the AI for African Languages Conference 2025
    Held in Kampala, Uganda on 10 October 2025

  Published as Volume 314 by the Proceedings of Machine Learning Research on 27 February 2026.

  Volume Edited by:
    Engineer Bainomugisha
    Ernest Mwebaze
    Richard Kimera
    Joyce Nakatumba Nabende
    Andrew Katumba
    John Quinn

  Series Editors:
    Neil D. Lawrence
date_str: 10 Oct
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v314"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v314
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v314
email: ''
conference:
  name: AI for African Languages Conference
  url: https://afrilangai.github.io/
  location: Kampala, Uganda
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: afrilang2025_cleaned_clean.bib
# Site settings
# Original source:  afrilang2025_cleaned_clean.bib
